### ISSUE TITLE
NanoKVM PCIe - no display, no IP

### ISSUE THREAD

**Issue by elf55** [sipeed/NanoKVM#291]
I have a new NanoKVM PCIe that just arrived and I've installed in single lane PCIe slot in a ZimaCube pro and connected the HDMI, USB, PoE Ethernet, and reset, power LED, and HDD pins.   The NanoKVM powers on and flashes the green LED on the back several times.  The Ethernet switch shows that link is up.  It never requests in IP address and the display panel is dark.  I have pressed the reset switch and held it down for two seconds without results.  The Ethernet link goes down and then comes back up and the green LED blinks a few times.  

I have put in a new SD card with firmware version 1.3.0 and see no different result.  

Can someone confirm that the device is broken or is there some other reason for it to be almost dead?

**Comment by iceton** [comment]
Can you feel your reset switch depress with a small click feeling? I encountered the same thing and my boot button was stuck. I removed the bracket and it worked as expected. The hole for the boot button seems to be too small so I will drill it out and reattach.

edit: enlarged the hole, reattached the bracket, problem solved.

**Comment by EnzoAlbornoz** [comment]
> Can you feel your reset switch depress with a small click feeling? I encountered the same thing and my boot button was stuck. I removed the bracket and it worked as expected. The hole for the boot button seems to be too small so I will drill it out and reattach.

Thank you very much! This helped me a lot. I managed to 3D-print an alternative bracket for it. I published it in Printables with an Open Source license:
https://www.printables.com/model/1256646-sipeed-nanokvm-pcie-bracket-full-height

**Comment by rmaeder** [comment]
my goodness! the half-height bracket breaks the boot switch. What a bad design. I reseated the bracket, and now it works.

**Comment by vodolaz095** [comment]
thanks for advice, i used circular rasp + hand drill to enlarge hole for `boot` button in smaller bracket and my KVM started to work! 
You have saved my day, @iceton!

but it is worth to notice i have stuck my KVM by static electricity when i have rubbed my hand thinking while installing it in my server - probably, it fixed things somehow %-)

**Comment by Stahlreck** [comment]
Can confirm, still the same issue with the small bracket. Kinda insane this hasn't been fixed. Ordered some of these recently and had to manually try to drill to make the hole bigger. From 2 to 3mm seemed to be enough already to fix it.
